# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # echo -n 'rootpassword' | base64
  user-password: dXNlcnBhc3N3b3Jk  # echo -n 'userpassword' | base64